# Generated by Django 5.0.7 on 2024-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_date_line_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_lin2e',
            field=models.DateTimeField(null=True),
        ),
    ]
