# Generated by Django 5.0.7 on 2024-07-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_date_lin2e'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_lin2e',
        ),
    ]
